k: 8
data: CyCIF1.csv
markers:
- Ki67
- CD45RB
- CD4
- CD163
- CD11b
- IBA1
- CD19
- LaminAC
- LAG3
- Keratin
- CD3
- CD45
- CD68
- FOXP3
- ASMA
- GFAP
- BANF1
- Arl13b
- PD1
- PDL1
- CD8A
- CD14
- CD21
- CD20
- gTubulin
- LaminB
